Repository Team-MoongChi/moongchi-fe, pull requests merged in 2025-06, with the labels that each got.

#8 [DESIGN] 쇼핑 페이지 필수 기능 틀 제작
  package-lock.json
  package.json
  src/assets/fonts/Hakgyoansim Dunggeunmiso OTF B.otf
  src/assets/fonts/Hakgyoansim Dunggeunmiso OTF R.otf
  src/assets/images/common/banner1.png
  src/assets/images/common/검색아이콘.png
  src/assets/images/common/배너버튼_오.png
  src/assets/images/common/배너버튼_왼.png
  src/assets/images/moongchies/AI뭉치_OFF.png
  src/assets/images/moongchies/AI뭉치_ON.png
  src/components/ShopItemPage/Header.tsx
  src/components/ShopItemPage/Main.tsx
  src/components/ShopItemPage/Nav.tsx
  src/components/ShopMainPage/Header.tsx
  src/components/ShopMainPage/Main.tsx
  src/components/ShopMainPage/Nav.tsx
  src/components/ShopResultPage/Header.tsx
  src/components/ShopResultPage/Main.tsx
  src/components/ShopResultPage/Nav.tsx
  src/index.css
  src/main.tsx
  src/pages/shoppingPages/ShopItemPage.tsx
  src/pages/shoppingPages/ShopMainPage.tsx
  src/pages/shoppingPages/ShopResultPage.tsx
  src/useDeviceSive.tsx
Labels: 🐱‍👤 지원, :pencil2: design

#10 [FEAT] 공구 글 작성 백엔드 연동
  src/components/gongguPages/gongguWritePage/Content.tsx
Labels: ✨ feat, :hamster: 하은

#12 [FEAT] 쇼핑 페이지 API 연동
  src/components/ShopMainPage/Nav.tsx
  src/components/ShopResultPage/Header.tsx
  src/components/ShopResultPage/Main.tsx
  src/components/ShopResultPage/Nav.tsx
  src/components/shoppingPages/ShopItemPage/Header.tsx
  src/components/shoppingPages/ShopItemPage/Main.tsx
  src/components/shoppingPages/ShopItemPage/Nav.tsx
  src/components/shoppingPages/ShopMainPage/Header.tsx
  src/components/shoppingPages/ShopMainPage/Main.tsx
  src/components/shoppingPages/ShopMainPage/Nav.tsx
  src/components/shoppingPages/ShopResultPage/Header.tsx
  src/components/shoppingPages/ShopResultPage/Main.tsx
  src/components/shoppingPages/ShopResultPage/Nav.tsx
  src/pages/shoppingPages/ShopItemPage.tsx
  src/pages/shoppingPages/ShopMainPage.tsx
  src/pages/shoppingPages/ShopResultPage.tsx
  src/routes/TotalRoutes.tsx
  src/routes/shoppingPage/ShoppngMainRoutes.tsx
Labels: ✨ feat, 🐱‍👤 지원

#17 [DESIGN] 공구 결제 화면 ui
  src/assets/images/gonggu/payed.png
  src/assets/images/gonggu/unpayed.png
  src/components/chatPages/chatListPage/ChatListItem.tsx
  src/components/chatPages/chatPayPage/Header.tsx
  src/components/chatPages/chatPayPage/UserCost.tsx
  src/components/chatPages/common/UserProfile.tsx
  src/pages/chatPages/AllReviewPage.tsx
  src/pages/chatPages/ChatListPage.tsx
  src/pages/chatPages/ChatPayPage.tsx
  src/pages/gongguPages/GongguItemPage.tsx
  src/pages/gongguPages/GongguMainPage.tsx
  src/routes/chatPage/ChatMainRoutes.tsx
  src/types/chatListPage/chatRoom.ts
Labels: :pencil2: design, :hamster: 하은

#19 [DESIGN] 시작 페이지 UI 구현
  src/assets/images/map/주방용품.png
  src/assets/images/map/주방용품_클릭.png
  src/assets/images/start/로그인_로고.png
  src/assets/images/start/안내1.png
  src/assets/images/start/안내2.png
  src/assets/images/start/안내3.png
  src/components/shoppingPages/ShopMainPage/Main.tsx
  src/components/startPages/LocationPage/Main.tsx
  src/components/startPages/LocationPage/Step.tsx
  src/components/startPages/PreferCategoryPage/Main.tsx
  src/components/startPages/PreferCategoryPage/Step.tsx
  src/components/startPages/UserDataPage/InputBox.tsx
  src/components/startPages/UserDataPage/InputBoxHalf.tsx
  src/components/startPages/UserDataPage/Main.tsx
  src/components/startPages/UserDataPage/Step.tsx
  src/components/startPages/common/Button.tsx
  src/components/startPages/startPage/SlideInfo.tsx
  src/pages/startPages/LocationPage.tsx
  src/pages/startPages/LoginPage.tsx
  src/pages/startPages/PreferCategoryPage.tsx
  src/pages/startPages/StartPage.tsx
  src/pages/startPages/UserDataPage.tsx
  src/routes/TotalRoutes.tsx
  src/routes/startPage/StartMainRoutes.tsx
Labels: 🐱‍👤 지원, :pencil2: design

#21 [FEAT] 시작 페이지 API 연동
  public/blue.png
  public/mint.png
  public/pink.png
  public/yellow.png
  src/components/startPages/PreferCategoryPage/Main.tsx
  src/components/startPages/UserDataPage/InputBox.tsx
  src/components/startPages/UserDataPage/InputBoxHalf.tsx
  src/components/startPages/UserDataPage/Main.tsx
  src/components/startPages/common/Button.tsx
  src/pages/startPages/LocationPage.tsx
  src/pages/startPages/LoginCallbackPage.tsx
  src/pages/startPages/LoginPage.tsx
  src/pages/startPages/PreferCategoryPage.tsx
  src/pages/startPages/StartPage.tsx
  src/pages/startPages/UserDataPage.tsx
  src/routes/TotalRoutes.tsx
  src/routes/chatPage/ChatMainRoutes.tsx
  src/routes/gongguPage/GongguMainRoutes.tsx
  src/routes/shoppingPage/ShoppngMainRoutes.tsx
  src/routes/startPage/StartMainRoutes.tsx
  vite.config.ts
Labels: ✨ feat, 🐱‍👤 지원

#25 [DESIGN] 마이페이지 ui 구현
  src/components/myPages/InterestPage/GongguListItem.tsx
  src/components/myPages/InterestPage/Header.tsx
  src/components/myPages/LocationPage/Button.tsx
  src/components/myPages/LocationPage/Header.tsx
  src/components/myPages/LocationPage/Main.tsx
  src/components/myPages/MyGongguPage/GongguListItem.tsx
  src/components/myPages/MyGongguPage/Header.tsx
  src/components/myPages/MyMainPage/Header.tsx
  src/components/myPages/MyMainPage/Menu.tsx
  src/components/myPages/MyMainPage/Nav.tsx
  src/components/myPages/MyMainPage/Profile.tsx
  src/components/myPages/ProfileEditPage/Button.tsx
  src/components/myPages/ProfileEditPage/Header.tsx
  src/components/myPages/ProfileEditPage/InputBox.tsx
  src/pages/myPages/InterestPage.tsx
  src/pages/myPages/LocationPage.tsx
  src/pages/myPages/MyGongguPage.tsx
  src/pages/myPages/MyMainPage.tsx
  src/pages/myPages/ProfileEditPage.tsx
  src/pages/shoppingPages/ShopItemPage.tsx
  src/pages/shoppingPages/ShopMainPage.tsx
  src/pages/shoppingPages/ShopResultPage.tsx
  src/pages/startPages/StartPage.tsx
  src/routes/TotalRoutes.tsx
  src/routes/myPage/MyMainRoutes.tsx
  src/useDeviceSive.tsx
Labels: 🐱‍👤 지원, :pencil2: design

#27 [FEAT] 변경된 쇼핑 검색 API 연동
  src/components/shoppingPages/ShopItemPage/Main.tsx
  src/components/shoppingPages/ShopItemPage/Nav.tsx
  src/components/shoppingPages/ShopMainPage/Main.tsx
  src/components/shoppingPages/ShopMainPage/Nav.tsx
  src/components/shoppingPages/ShopResultPage/Nav.tsx
  src/pages/shoppingPages/ShopItemPage.tsx
  src/pages/shoppingPages/ShopResultPage.tsx
  src/pages/startPages/PreferCategoryPage.tsx
  src/pages/startPages/UserDataPage.tsx
  src/utils/FetchWithAuth.tsx
Labels: ✨ feat, 🐱‍👤 지원

#30 [DESIGN] 공용 컴포넌트 제작
  src/components/common/Header.tsx
  src/components/common/Nav.tsx
  src/components/myPages/LocationPage/Header.tsx
  src/components/myPages/MyGongguPage/Header.tsx
  src/components/myPages/MyMainPage/Nav.tsx
  src/components/myPages/ProfileEditPage/Header.tsx
  src/components/shoppingPages/ShopItemPage/Header.tsx
  src/components/shoppingPages/ShopMainPage/Nav.tsx
  src/components/shoppingPages/ShopResultPage/Nav.tsx
  src/pages/myPages/InterestPage.tsx
  src/pages/myPages/LocationPage.tsx
  src/pages/myPages/MyGongguPage.tsx
  src/pages/myPages/MyMainPage.tsx
  src/pages/myPages/ProfileEditPage.tsx
  src/pages/shoppingPages/ShopItemPage.tsx
  src/pages/shoppingPages/ShopMainPage.tsx
  src/pages/shoppingPages/ShopResultPage.tsx
Labels: 🐱‍👤 지원, :pencil2: design

#32 [FEAT] 마이페이지 API 연동
  .gitignore
  index.html
  package-lock.json
  package.json
  src/assets/images/common/사진없을때.png
  src/assets/images/common/위치마커.png
  src/components/myPages/MyMainPage/Menu.tsx
  src/components/myPages/MyMainPage/Profile.tsx
  src/components/myPages/ProfileEditPage/InputBox.tsx
  src/components/shoppingPages/ShopItemPage/Main.tsx
  src/components/shoppingPages/ShopMainPage/Main.tsx
  src/components/shoppingPages/ShopResultPage/Main.tsx
  src/components/startPages/LocationPage/Main.tsx
  src/components/startPages/PreferCategoryPage/Main.tsx
  src/components/startPages/UserDataPage/InputBox.tsx
  src/components/startPages/UserDataPage/Main.tsx
  src/components/startPages/startPage/SlideInfo.tsx
  src/pages/myPages/InterestPage.tsx
  src/pages/myPages/LocationPage.tsx
  src/pages/myPages/MyGongguPage.tsx
  src/pages/myPages/ProfileEditPage.tsx
  src/pages/shoppingPages/ShopMainPage.tsx
  src/pages/startPages/LocationPage.tsx
Labels: ✨ feat, 🐱‍👤 지원

#45 [DESIGN] 뭉치 애니메이션 추가
  src/assets/images/start/로그인_로고2.gif
  src/assets/images/start/뭉치박스.gif
  src/assets/images/start/안내1_2.gif
  src/assets/images/start/안내2_2.gif
  src/assets/images/start/안내3_2.gif
  src/components/startPages/startPage/SlideInfo.tsx
  src/pages/startPages/LoginPage.tsx
Labels: 🐱‍👤 지원, :pencil2: design

#48 [FIX] 유저 관련 API 버그 수정
  src/components/myPages/MyMainPage/Menu.tsx
  src/components/startPages/common/Button.tsx
  src/pages/startPages/LocationPage.tsx
  src/pages/startPages/PreferCategoryPage.tsx
  src/pages/startPages/UserDataPage.tsx
Labels: :wrench: fix, 🐱‍👤 지원

#52 [DESIGN] 공구 관련 ui 보완
  src/assets/images/gonggu/angle-square-left.png
  src/assets/images/gonggu/angle-square-right.png
  src/components/gongguPages/gongguItemPage/ImageSlide.tsx
Labels: :pencil2: design, :hamster: 하은

#55 [FIX] fetchWithAuth
  src/components/gongguPages/gongguItemPage/Footer.tsx
  src/components/gongguPages/gongguWritePage/Content.tsx
  src/pages/chatPages/AllReviewPage.tsx
  src/pages/chatPages/ChatPage.tsx
  src/pages/chatPages/ChatPayPage.tsx
  src/pages/chatPages/OneReviewPage.tsx
  src/pages/gongguPages/GongguItemPage.tsx
  src/pages/gongguPages/GongguMainPage.tsx
  src/pages/startPages/LoginCallbackPage.tsx
  src/pages/startPages/PreferCategoryPage.tsx
  src/utils/FetchWithAuth.tsx
Labels: :wrench: fix, 🐱‍👤 지원

#59 [FEAT] 쇼핑 상세에서 공구 생성으로 데이터 넘기기
  src/components/shoppingPages/ShopItemPage/Nav.tsx
  src/pages/shoppingPages/ShopItemPage.tsx
Labels: ✨ feat, 🐱‍👤 지원

#61 [DESIGN] 쇼핑 챗봇 페이지 퍼블리싱
  src/assets/images/moongchies/로딩중.gif
  src/components/common/Loading.tsx
  src/components/shoppingPages/ShopChatbotPage/AIChat.tsx
  src/components/shoppingPages/ShopChatbotPage/IChat.tsx
  src/components/shoppingPages/ShopChatbotPage/Main.tsx
  src/components/shoppingPages/ShopChatbotPage/Nav.tsx
  src/components/shoppingPages/ShopItemPage/Nav.tsx
  src/components/shoppingPages/ShopMainPage/Header.tsx
  src/pages/shoppingPages/ShopMainPage.tsx
  src/pages/shoppingPages/shopChatBotPage.tsx
  src/routes/shoppingPage/ShoppngMainRoutes.tsx
Labels: 🐱‍👤 지원, :pencil2: design

#64 [DESIGN] 내가 올린 공구 메인 디자인 수정
  src/assets/images/common/뒤로가기.png
  src/components/common/Header.tsx
  src/components/shoppingPages/ShopItemPage/Header.tsx
  src/components/shoppingPages/ShopResultPage/Header.tsx
  src/pages/myPages/MyGongguPage.tsx
Labels: 🐱‍👤 지원, :pencil2: design

#67 [REFACTOR] 로그인 안 되어 있을 때 시작 페이지로 이동하기
  src/assets/images/start/안내1_2.gif
  src/utils/FetchWithAuth.tsx
Labels: ♻️ refactor, 🐱‍👤 지원

#69 [FEAT] API 호출 로딩 구현
  src/components/myPages/MyMainPage/Menu.tsx
  src/components/myPages/MyMainPage/Profile.tsx
  src/components/shoppingPages/ShopMainPage/Header.tsx
Labels: ✨ feat, 🐱‍👤 지원

#71 [FIX] 경로 오타 수정
  src/pages/shoppingPages/shopChatBotPage.tsx
Labels: :wrench: fix, 🐱‍👤 지원

#76 [FEAT] 공구 상세에서 리더 프로필 상세 모달 띄우기
  src/components/gongguPages/gongguItemPage/Content.tsx
  src/components/gongguPages/gongguItemPage/Profile.tsx
Labels: ✨ feat, 🐱‍👤 지원, :pencil2: design

#78 [FEAT] 상품 상세 페이지 공구 리스트에 사용자가 만든 공구는 비활성화
  src/components/shoppingPages/ShopItemPage/GongguCountdown.tsx
  src/components/shoppingPages/ShopItemPage/Main.tsx
  src/components/startPages/PreferCategoryPage/Main.tsx
Labels: ✨ feat, :wrench: fix, 🐱‍👤 지원, :pencil2: design

#80 [FEAT] 뒤로가기 & 공구 공유 기능 구현
  index.html
  src/components/common/Header.tsx
  src/components/gongguPages/common/GongguListItem.tsx
  src/components/gongguPages/gongguItemPage/GotoShop.tsx
  src/components/gongguPages/gongguItemPage/Header.tsx
  src/components/gongguPages/gongguMainPage/GongguSearchBar.tsx
  src/components/gongguPages/gongguMainPage/MenuButton.tsx
  src/components/myPages/InterestPage/GongguListItem.tsx
  src/components/myPages/MyGongguPage/GongguListItem.tsx
  src/components/myPages/MyMainPage/Profile.tsx
  src/components/shoppingPages/ShopItemPage/Header.tsx
  src/components/shoppingPages/ShopItemPage/Main.tsx
  src/components/shoppingPages/ShopItemPage/Nav.tsx
  src/components/shoppingPages/ShopMainPage/Header.tsx
  src/components/shoppingPages/ShopMainPage/Main.tsx
  src/components/shoppingPages/ShopResultPage/Header.tsx
  src/components/shoppingPages/ShopResultPage/Main.tsx
  src/pages/gongguPages/GongguItemPage.tsx
  src/pages/gongguPages/GongguMainPage.tsx
  src/pages/gongguPages/GongguMapPage.tsx
  src/pages/gongguPages/GongguSearchPage.tsx
  src/pages/myPages/InterestPage.tsx
  src/pages/myPages/MyGongguPage.tsx
  src/pages/shoppingPages/ShopResultPage.tsx
  src/utils/useHistoryStack.tsx
  src/vite-env.d.ts
Labels: ✨ feat, 🐱‍👤 지원

#82 [FIX] 세션 버그 픽스 & 뭉치픽 세션 뒤로가기 구현
  src/components/shoppingPages/ShopMainPage/Main.tsx
  src/components/shoppingPages/ShopMainPage/MoongchiPick.tsx
Labels: ✨ feat, :wrench: fix, 🐱‍👤 지원

#87 [FIX] 배포 시 빌드 오류 수정 - 채팅 제외
  src/components/common/Header.tsx
  src/components/gongguPages/common/GongguListItem.tsx
  src/components/gongguPages/gongguItemPage/Header.tsx
  src/components/gongguPages/gongguItemPage/Profile.tsx
  src/components/gongguPages/gongguMapPage/GongguMap.tsx
  src/components/gongguPages/gongguWritePage/AddressModal.tsx
  src/components/myPages/MyMainPage/Profile.tsx
  src/components/myPages/ProfileEditPage/InputBox.tsx
  src/components/shoppingPages/ShopChatbotPage/Main.tsx
  src/components/shoppingPages/ShopItemPage/Main.tsx
  src/components/shoppingPages/ShopItemPage/Nav.tsx
  src/components/shoppingPages/ShopMainPage/Header.tsx
  src/components/shoppingPages/ShopMainPage/Main.tsx
  src/components/shoppingPages/ShopResultPage/Header.tsx
  src/components/startPages/LocationPage/Main.tsx
  src/components/startPages/UserDataPage/InputBox.tsx
  src/components/startPages/UserDataPage/Main.tsx
  src/pages/gongguPages/GongguMapPage.tsx
  src/pages/myPages/LocationPage.tsx
  src/pages/myPages/MyGongguPage.tsx
  src/pages/myPages/ProfileEditPage.tsx
  src/pages/shoppingPages/ShopResultPage.tsx
  src/pages/shoppingPages/shopChatBotPage.tsx
  src/pages/startPages/UserDataPage.tsx
  src/routes/shoppingPage/ShoppngMainRoutes.tsx
Labels: :wrench: fix, 🐱‍👤 지원

#89 [DESIGN] 공구 상세에서 참여 시 안내 모달 띄우기
  src/components/common/ParticipantsProfile.tsx
  src/components/gongguPages/gongguItemPage/Footer.tsx
  src/components/myPages/MyMainPage/Menu.tsx
  src/components/myPages/MyMainPage/Profile.tsx
  src/components/shoppingPages/ShopItemPage/Main.tsx
Labels: 🐱‍👤 지원, :pencil2: design

#93 [FEAT] 비로그인일 때 공구 상세 확인가능
  src/components/gongguPages/gongguItemPage/Footer.tsx
  src/components/gongguPages/gongguItemPage/Profile.tsx
  src/pages/gongguPages/GongguItemPage.tsx
Labels: ✨ feat, 🐱‍👤 지원

#99 [REFACTOR] 배포된 서버로 변경
  src/components/gongguPages/gongguItemPage/Footer.tsx
  src/components/gongguPages/gongguItemPage/Profile.tsx
  src/pages/gongguPages/GongguItemPage.tsx
  src/pages/startPages/LoginCallbackPage.tsx
  src/pages/startPages/LoginPage.tsx
  src/utils/FetchWithAuth.tsx
  vite.config.ts
Labels: ♻️ refactor, 🐱‍👤 지원

#101 [DESIGN] 모바일 input date 디자인 수정
  src/components/startPages/UserDataPage/InputBoxHalf.tsx
Labels: 🐱‍👤 지원, :pencil2: design

#106 [FEAT] 쇼핑 추천 아이템 API 연동
  src/components/shoppingPages/ShopMainPage/MoongchiPick.tsx
Labels: ✨ feat, 🐱‍👤 지원

#108 [FIX] 공구 목록에서 참여자 프로필 렌더링 수정
  src/components/common/ParticipantsProfile.tsx
  src/components/gongguPages/gongguMainPage/RecPartProfile.tsx
Labels: :wrench: fix, :hamster: 하은

#110 [REFACTOR] 소켓 연결 최적화
  src/components/chatPages/chatListPage/ChatListItem.tsx
  src/components/chatPages/chatPage/SocketConnect.tsx
  src/components/chatPages/chatPage/systemMsg/ChatInput.tsx
  src/components/chatPages/chatPayPage/PayHeader.tsx
  src/components/gongguPages/gongguItemPage/Footer.tsx
  src/pages/chatPages/AllReviewPage.tsx
  src/pages/chatPages/ChatPage.tsx
  src/routes/chatPage/ChatMainRoutes.tsx
  src/types/chatPages/chatRoomItem.ts
Labels: ♻️ refactor, :hamster: 하은

#111 [FEAT] 챗봇 API 변경 및 세션 적용
  src/assets/images/moongchies/AI뭉치_OFF.png
  src/assets/images/moongchies/AI뭉치_ON.png
  src/components/shoppingPages/ShopChatbotPage/AIChat.tsx
  src/components/shoppingPages/ShopChatbotPage/Header.tsx
  src/components/shoppingPages/ShopChatbotPage/Main.tsx
  src/components/shoppingPages/ShopChatbotPage/Nav.tsx
  src/components/shoppingPages/ShopChatbotPage/TypingText.tsx
  src/components/shoppingPages/ShopMainPage/Header.tsx
  src/components/shoppingPages/ShopMainPage/Main.tsx
  src/components/shoppingPages/ShopMainPage/MoongchiPick.tsx
  src/pages/shoppingPages/ShopChatbotPage.tsx
  vercel.json
  vite.config.ts
Labels: ✨ feat, 🐱‍👤 지원

#113 [DESIGN] 메인, 채팅 페이지 로딩 추가
  src/components/gongguPages/gongguMainPage/GongguRecommend.tsx
  src/pages/chatPages/ChatListPage.tsx
  src/pages/gongguPages/GongguMainPage.tsx
Labels: 🐱‍👤 지원, :pencil2: design

#115 [DESIGN] 모바일 ui 수정
  package-lock.json
  package.json
  src/components/chatPages/chatPage/ChatConnect.tsx
  src/components/chatPages/chatPage/SocketConnect.tsx
  src/pages/chatPages/AllReviewPage.tsx
  src/pages/chatPages/ChatPage.tsx
  src/pages/chatPages/ChatPayPage.tsx
  src/pages/chatPages/OneReviewPage.tsx
Labels: ✨ feat, :pencil2: design, :hamster: 하은
